window:
  width: 1024
  height: 768
  hide_titlebar: true
  corner_radius: 8.0
  padding:
    top: 20
    bottom: 20
    left: 20
    right: 20
terminal:
  write_speed: 8192
  rows: 25
  cols: 78
font:
  path: /usr/share/fonts/TTF/DejaVuSansMono.ttf
  size: 32
  char_spacing: 1.0
  line_spacing: 1.0
colors:
  background:
  - 0.125
  - 0.137
  - 0.149
  - 1.0
  text:
  - 0.243
  - 0.255
  - 0.271
  - 1.0
  glow:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  selection:
  - 0.5
  - 0.5
  - 0.5
  - 0.3
cursor:
  shape: '0x2506'
  blink: true
scrollbar:
  mode: auto
effects:
  glow:
    intensity: 0.0
    spread: 1.0
  vignette:
    enabled: true
    strength: 0.66
  scanlines:
    enabled: false
    intensity: 0.2
    frequency: 0.5
  curvature:
    enabled: false
    amount: 0.02
  burn_in:
    enabled: false
    intensity: 1.0
    build: 0.5
    fade_time: 0.1
    tint:
    - 0.25
    - 0.25
    - 0.25
    - 1.0
